Zadatak1
lukaendava/luka_ivancic_java_zadaci pull request #2
Opened 2019-10-08 16:03 UTC by lukaendava

2019-10-09 08:42 UTC, endavamarko requested changes

2019-10-09 08:42 UTC, endavamarko commented on src/zadatak1/Main.java
> +
Ovde treba try/catch blok bez obzira sto nema unosa uhvatice bilo koji izuzetak koji je prosledjen

2019-10-09 08:42 UTC, endavamarko commented on src/zadatak1/Nekretnina.java
> +        this.zona = zona;
ovde treba provera da nije negativan broj unesen

2019-10-09 08:42 UTC, endavamarko commented on src/zadatak1/Vlasnik.java
> +        this.jmbg = jmbg;
ubaciti proveru da li ima 13 karaktera

2019-10-09 08:42 UTC, endavamarko commented on src/zadatak1/Vlasnik.java
> +        this.brojLicneKarte = brojLicneKarte;
ubaciti proveru broja licne karte

2019-10-10 08:28 UTC, endavamarko approved these changes

2019-10-10 08:28 UTC, endavamarko commented on src/zadatak1/Kuca.java
> +    public Kuca(String adresa, int zona, double kvadratura, Vlasnik vlasnik, double povrsinaOkucnice) throws Exception {
Ovo moze da prodje, ali nije dobra praksa da konstruktor baca exception. U svakom slucjau cilj ove vezbe sa Java zadacima je i vezba rada sa git-om, tako da mozes da merge-ujes na master granu

2019-10-10 08:28 UTC, endavamarko commented on src/zadatak1/Nekretnina.java
> +    public Nekretnina(String adresa, int zona, double kvadratura, Vlasnik vlasnik) throws Exception {
Ovo moze da prodje, ali nije dobra praksa da konstruktor baca exception. U svakom slucjau cilj ove vezbe sa Java zadacima je i vezba rada sa git-om, tako da mozes da merge-ujes na master granu

2019-10-10 08:28 UTC, endavamarko commented on src/zadatak1/Vlasnik.java
> +    public Vlasnik(String imeIPrezime, String jmbg, String brojLicneKarte) throws Exception {
Ovo moze da prodje, ali nije dobra praksa da konstruktor baca exception. U svakom slucjau cilj ove vezbe sa Java zadacima je i vezba rada sa git-om, tako da mozes da merge-ujes na master granu

2019-10-10 09:22 UTC, lukaendava commented
Svestan sam da nije najbolja praksa da konstruktor baca izuzetke i internet je tako rekao, ali krenuo jsam ovako uce, pa sam isterao do kraja. Danas vec imam neka bolja resenja, ali ako je ipak poenta u GIT-u, onda neka ostane kako je.

2019-10-10 09:22 UTC, merged